routes/dashboard.php
<?php
use Illuminate\Support\Facades\Route;
Route::prefix('dashboard')->name('dashboard.')->middleware(['auth'])->group(function () {
    Route::post('/register', '\App\Http\Controllers\Auth\RegisterController@register')->name('register');

    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/contact/us', 'DashboardController@contactUs')->name('contact_us');

    Route::get('/change/password', 'DashboardController@change_password')->name('change_password');
    Route::post('/change/password/user', 'DashboardController@change_password_user')->name('change_password_user');

    Route::post('property/{property}/active/toggle','PropertyCtrl@toggleActive')->name('property.toggleActive');
    Route::post('contact/{contact}/status/read_at','ContactCtrl@toggleStatus')->name('contact.toggleStatus');

    Route::resource('developer','DevCtrl')->except(['show','store','update']);
    Route::resource('user','UserCtrl');
    Route::resource('project','ProjectCtrl');
    Route::resource('owner','OwnerCtrl');
    Route::resource('setting','SettingCtrl');
    Route::resource('property','PropertyCtrl');
    Route::resource('contact','ContactCtrl');
    Route::resource('region','RegionCtrl');
    Route::resource('blog','BlogCtrl');
    Route::resource('unitTypes','UnitTypesCtrl');
    Route::resource('slider','SliderController');

});

Route::get('{type}/{region}/{city}/{property:slug}/{name}','\App\Http\Controllers\FrontController@SingleProperty')->name('single.property')->where('type','resale|rent');

Route::get('rent/{region?}/{city?}/{street?}/{type_for?}','\App\Http\Controllers\FrontController@rant')->name('rent');
Route::get('resale/{region?}/{city?}/{street?}/{type_for?}','\App\Http\Controllers\FrontController@resale')->name('resale');

Route::get('/{location}/{developer:slug}/{project:slug?}','\App\Http\Controllers\FrontController@SingleProject')->name('developer_project.show');


Route::get('/{developer:slug}','\App\Http\Controllers\FrontController@show')->name('developer.show');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register'=>false]);

Route::redirect('/home', '/dashboard')->name('home');

Route::get('setLocale/{locale?}', 'FrontController@setLocale')->where('locale','en|ar')->name('locale');

Route::get('/','FrontController@main')->name('main');

Route::get('dashboard','FrontController@dashboard')->name('dashboard');
Route::get('pricing','FrontController@pricing')->name('pricing');
Route::get('location/{location:slug}','FrontController@location')->name('location');
Route::get('about','FrontController@about')->name('about_us');
Route::get('developer','FrontController@developers_page')->name('developer.index');
//Route::get('developer/{developer:slug}/projects/{project}','FrontController@SingleProject')->name('developer_project.show');
//Route::get('developer/{developer:slug}','FrontController@show')->name('developer.show');


Route::get('contact','FrontController@contact_create')->name('contact_us');

Route::post('contact_project_post/{project}','FrontController@contact_project_post')->name('contact_project_post');

Route::post('contact_property_post/{property}','FrontController@contact_property_post')->name('contact_property_post');

Route::get('project','FrontController@project')->name('project');
Route::get('property','FrontController@SubmitProperty')->name('SubmitProperty');
//Route::get('property/{property:slug}','FrontController@SingleProperty')->name('single.property');
//Route::get('project/{project:slug}','FrontController@SingleProject')->name('single.project');
Route::get('blog/{blog:slug}','FrontController@SingleBlog')->name('single.blog');
Route::get('blogs/','FrontController@blogs')->name('blogs');
//Route::get('rent','FrontController@rant')->name('rent');
//Route::get('resale','FrontController@resale')->name('resale');

Route::get('autocomplete','FrontController@autocomplete')->name('autocomplete');

Route::get('/home', 'HomeController@index')->name('change_locale');

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HasAvatar;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Traits\HasPassword;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class User extends Authenticatable{
    use Notifiable,SoftDeletes,LogsActivity,HasPassword,HasSlug,HasAvatar;
    public static function avatarFiled(){ return 'image'; }
    public const USER_ID = "user_id";

    protected $fillable = [
        'name', 'email', 'password','image','phone','locale','is_admin'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $dateFormat="Y-m-d";
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean',
    ];

    public function getSlugOptions() : SlugOptions{
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    public function isAdmin(){ return $this->is_admin; }

    protected static function boot(){
        parent::boot();
        static::creating(function (Model $model) {
            $model->locale = $model->locale  ?? app()->getLocale();
            $model->is_admin = $model->is_admin  ?? false;
            $model->phone = $model->phone  ?? null;
        });
    }

}

app/Http/Controllers/Dashboard/BlogCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Blog\BlogCreateRequest;
use App\Http\Requests\Blog\BlogUpdateRequest;
use App\Models\Blog;
use Illuminate\Http\Request;

class BlogCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() {
        return view('dashboard.blog.index',['blogs'=>Blog::latest()->get()]);
    }

    public function create(){ return view('dashboard.blog.create'); }


    public function store(BlogCreateRequest $request){
        $validated=$request->validated();
        if ($request->hasFile(Blog::avatarFiled()??'image')) $validated[Blog::avatarFiled()??'image']=uploader($request->file(Blog::avatarFiled()??'image'));
        Blog::create($validated);
        alert()->success(__('main.blog'),__('main.created'));
        return  back();
    }

    public function show(Blog $blog){ return view('dashboard.blog.show',compact('blog')); }

    public function edit(Blog $blog){ return view('dashboard.blog.edit',compact('blog')); }

    public function update(BlogUpdateRequest $request, Blog $blog){
        $validated=$request->validated();
        if ($request->hasFile(Blog::avatarFiled()??'image')) $validated[Blog::avatarFiled()??'image']=uploader($request->file(Blog::avatarFiled()??'image'));
        $blog->update($validated);
        alert()->success(__('main.blog'),__('main.updated'));
        return  back();

    }

    public function destroy(Blog $blog){
        $blog->delete();
        alert()->success(__('main.blog'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/ContactCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContactCreateRequest;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }

    public function toggleStatus(Contact $contact){
        $contact->update(['read_at' => now()]);
        return back()->withSuccess(__('main.mark_as_read'));
    }
    public function index() { return view('dashboard.contact.index'); }

//    public function create(){ return view('dashboard.contact.create'); }


    public function store(ContactCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Contact::avatarSelectedFiled()??'image')) $validated[Contact::avatarSelectedFiled()??'image'];
        Contact::create($validated);
        alert()->success(__('main.contact'),__('main.created'));
        return  back();
    }

//    public function show(Contact $contact){ return view('dashboard.contact.show',compact('contact')); }

//    public function edit(Contact $contact){ return view('dashboard.contact.edit',compact('contact')); }
//
//    public function update(ContactUpdateRequest $request, Contact $contact){
//        $validated=$request->validated();
//        //if ($request->hasFile(Contact::avatarSelectedFiled()??'image')) $validated[Contact::avatarSelectedFiled()??'image'];
//        $contact->update($validated);
//        alert()->success(__('main.contact'),__('main.updated'));
//        return  back();
//
//    }

    public function destroy(Contact $contact){
        $contact->delete();
        alert()->success(__('main.contact'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\User;
use foo\bar;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class DashboardController extends Controller{

    public function index() { return view('dashboard.blank'); }

    public function contactUs(){ return view('dashboard.contact'); }
    //
    public function change_password(){ return view('dashboard.profile.change_password'); }
    public function change_password_user(Request $request){
        $request->validate([
            'current_password' => ['required', 'string', 'min:8'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        $user=auth()->user();
        /**
         * @var $user User
         */
        if (!$user->comparePassword($request->get('current_password'))){
            return back()->withErrors([ "current_password"=>__('main.current_password_not_match')]);
        }



        if ($user->comparePassword($request->get('password'))){
            alert()->info(__('main.profile'),__('main.password_old_and_new_same'));
        }else{
            $user->update([
                'password' => $request->get('password')
            ]);
            alert()->success(__('main.profile'),__('main.password_changed_success'));
        }
        return back();
    }

}

app/Http/Controllers/Dashboard/DevCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Developer;
use Exception;

class DevCtrl extends Controller{

    public function index(){ return view('dashboard.developer.index'); }
    public function create(){ return view('dashboard.developer.create'); }
    public function show(Developer $developer){ return view('dashboard.developer.show',compact('developer')); }

    public function delete(Developer $developer){
        try {
            $developer->delete();
            alert()->success(__('main.developer'),__('main.developer_deleted'));
        } catch (Exception $e) {
        alert()->error(__('main.error_title_ERORR',$e->getMessage()));
        }
        return back();
    }

    public function edit(Developer $developer){ return view('dashboard.developer.edit',compact('developer')); }

}

app/Http/Controllers/Dashboard/OwnerCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Owner\OwnerCreateRequest;
use App\Http\Requests\Owner\OwnerUpdateRequest;
use App\Models\Owner;
use Illuminate\Http\Request;

class OwnerCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.owner.index'); }

    public function create(){ return view('dashboard.owner.create'); }


    public function store(OwnerCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Owner::avatarSelectedFiled()??'image')) $validated[Owner::avatarSelectedFiled()??'image'];
        Owner::create($validated);
        alert()->success(__('main.owner'),__('main.created'));
        return  back();
    }

    public function show(Owner $owner){ return view('dashboard.owner.show',compact('owner')); }

    public function edit(Owner $owner){ return view('dashboard.owner.edit',compact('owner')); }

    public function update(OwnerUpdateRequest $request, Owner $owner){
        $validated=$request->validated();
        //if ($request->hasFile(Owner::avatarSelectedFiled()??'image')) $validated[Owner::avatarSelectedFiled()??'image'];
        $owner->update($validated);
        alert()->success(__('main.owner'),__('main.updated'));
        return  back();

    }

    public function destroy(Owner $owner){
        $owner->delete();
        alert()->success(__('main.owner'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/ProjectCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Project\ProjectCreateRequest;
use App\Http\Requests\Project\ProjectUpdateRequest;
use App\Models\Project;
use Illuminate\Http\Request;

class ProjectCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.project.index'); }

    public function create(){ return view('dashboard.project.create'); }


    public function store(ProjectCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Project::avatarSelectedFiled()??'image')) $validated[Project::avatarSelectedFiled()??'image'];
        Project::create($validated);
        alert()->success(__('main.project'),__('main.created'));
        return  back();
    }

    public function show(Project $project){ return view('dashboard.project.show',compact('project')); }

    public function edit(Project $project){ return view('dashboard.project.edit',compact('project')); }

    public function update(ProjectUpdateRequest $request, Project $project){
        $validated=$request->validated();
        //if ($request->hasFile(Project::avatarSelectedFiled()??'image')) $validated[Project::avatarSelectedFiled()??'image'];
        $project->update($validated);
        alert()->success(__('main.project'),__('main.updated'));
        return  back();

    }

    public function destroy(Project $project){
        $project->delete();
        alert()->success(__('main.project'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/PropertyCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Property\PropertyCreateRequest;
use App\Http\Requests\Property\PropertyUpdateRequest;
use App\Models\Property;
use Illuminate\Http\Request;

class PropertyCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.property.index'); }

    public function create(){ return view('dashboard.property.create'); }

    public function toggleActive(Property $property){
        $property->update(['active' => !$property->active]);
        return back()->withSuccess($property->active?__('main.active'):__('main.not_active'));
    }

    public function store(PropertyCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Property::avatarSelectedFiled()??'image')) $validated[Property::avatarSelectedFiled()??'image'];
        Property::create($validated);
        alert()->success(__('main.property'),__('main.created'));
        return  back();
    }

    public function show(Property $property){ return view('dashboard.property.show',compact('property')); }

    public function edit(Property $property){ return view('dashboard.property.edit',compact('property')); }

    public function update(PropertyUpdateRequest $request, Property $property){
        $validated=$request->validated();
        //if ($request->hasFile(Property::avatarSelectedFiled()??'image')) $validated[Property::avatarSelectedFiled()??'image'];
        $property->update($validated);
        alert()->success(__('main.property'),__('main.updated'));
        return  back();

    }

    public function destroy(Property $property){
        $property->delete();
        alert()->success(__('main.property'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/SettingCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Setting\SettingCreateRequest;
use App\Http\Requests\Setting\SettingUpdateRequest;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingCtrl extends Controller{
    public function __construct(){ $this->middleware(['auth']); }

    public function index() { return view('dashboard.setting.index'); }

    public function update(SettingUpdateRequest $request, Setting $setting){
        $validated=$request->validated();
        //if ($request->hasFile(Setting::avatarSelectedFiled()??'image')) $validated[Setting::avatarSelectedFiled()??'image'];
        $setting->update($validated);
        alert()->success(__('main.setting'),__('main.updated'));
        return  back();

    }

    public function destroy(Setting $setting){
        $setting->delete();
        alert()->success(__('main.setting'),__('main.deleted'));
        return  back();
    }

}

app/View/Components/Dashboard/Header.php
<?php

namespace App\View\Components\Dashboard;

use Illuminate\View\Component;

class Header extends Component{

    public function render(){
        return view('components.dashboard.header');
    }
}

resources/views/dashboard/user/create.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>trans('main.user_create')])
        <form method="POST" action="{{ route('dashboard.register') }}">
            @csrf

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('main.name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"  placeholder="@lang('main.name')" value="{{ old('name') }}" required autocomplete="name" autofocus>

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">@lang('main.email')</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" placeholder="@lang('main.email')"  name="email" value="{{ old('email') }}" required autocomplete="email">

                    @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">@lang('main.password')</label>

                <div class="col-md-6">
                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" placeholder="@lang('main.password')"  name="password" required autocomplete="new-password">

                    @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">@lang('main.password_confirmation')</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" placeholder="@lang('main.password_confirmation')"  required autocomplete="new-password">
                </div>
            </div>


            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('main.is_admin') }}</label>

                <div class="col-md-6">
                    <div class="custom-control custom-radio custom-control-inline @error('is_admin') is-invalid @enderror">
                        <input type="radio" id="customRadioInline1" checked value="1" name="is_admin" class="custom-control-input">
                        <label class="custom-control-label" for="customRadioInline1">@lang('main.yes')</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline @error('is_admin') is-invalid @enderror">
                        <input type="radio" id="customRadioInline2" name="is_admin" value="0" class="custom-control-input">
                        <label class="custom-control-label" for="customRadioInline2">@lang('main.no')</label>
                    </div>

                    @error('is_admin')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>


            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('main.register') }}
                    </button>
                </div>
            </div>
        </form>
    @endcomponent


@stop

resources/views/dashboard/user/edit.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>trans('main.user_edit')])
        <form method="POST" action="{{ route('dashboard.user.update',$user) }}">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('main.name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"  placeholder="@lang('main.name')" value="{{ old('name',$user->name) }}" required autocomplete="name" autofocus>

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('main.email') }}</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" placeholder="@lang('main.email')"  name="email" value="{{ old('email',$user->email) }}" required autocomplete="email">

                    @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('main.is_admin') }}</label>

                <div class="col-md-6">
                    <div class="custom-control custom-radio custom-control-inline @error('is_admin') is-invalid @enderror">
                        <input type="radio" id="customRadioInline1" {{$user->is_admin?' checked ':""}} value="1" name="is_admin" class="custom-control-input">
                        <label class="custom-control-label" for="customRadioInline1">@lang('main.yes')</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline @error('is_admin') is-invalid @enderror">
                        <input type="radio" id="customRadioInline2" {{!$user->is_admin?' checked ':""}} name="is_admin" value="0" class="custom-control-input">
                        <label class="custom-control-label" for="customRadioInline2">@lang('main.no')</label>
                    </div>

                    @error('is_admin')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-warning btn-sm">
                        {{ __('main.update') }}
                    </button>
                </div>
            </div>
        </form>

    @endcomponent


@stop

resources/views/dashboard/user/index.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>ucfirst(trans('main.users'))])

        <table class="table table-hover  table-sm">
            <thead class="thead-default">
            <tr>
                <th>@lang('main.id')</th>
                <th>@lang('main.name')</th>
                <th>@lang('main.email')</th>
                <th>@lang('main.is_admin')</th>
                <th>@lang('main.edit')</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($users ?? \App\Models\User::latest()->get() as $user)
            <tr>
                <td scope="row">{{$loop->index+1}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td class="{{$user->is_admin?' text-success ':' text-danger '}}">{{$user->is_admin?__('main.admin'):__('main.not_admin')}}</td>
                <td><a href="{{route('dashboard.user.edit',$user)}}" class="btn btn-sm btn-warning">@lang('main.edit')</a></td>
            </tr>
            @endforeach
            </tbody>
        </table>

    @endcomponent


@stop

resources/views/dashboard/user/show.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>trans('main.developer')])


    @endcomponent


@stop