routes/dashboard.php
<?php
use Illuminate\Support\Facades\Route;
Route::prefix('dashboard')->name('dashboard.')->middleware(['auth'])->group(function () {
    Route::post('/register', '\App\Http\Controllers\Auth\RegisterController@register')->name('register');

    Route::get('/', 'DashboardController@index')->name('home');

    Route::get('/contact/us', 'DashboardController@contactUs')->name('contact_us');

    Route::get('/change/password', 'DashboardController@change_password')->name('change_password');
    Route::post('/change/password/user', 'DashboardController@change_password_user')->name('change_password_user');

    Route::post('property/{property}/active/toggle','PropertyCtrl@toggleActive')->name('property.toggleActive');
    Route::post('contact/{contact}/status/read_at','ContactCtrl@toggleStatus')->name('contact.toggleStatus');

    Route::resource('developer','DevCtrl')->except(['show','store','update']);
    Route::resource('user','UserCtrl');
    Route::resource('project','ProjectCtrl');
    Route::resource('owner','OwnerCtrl');
    Route::resource('setting','SettingCtrl');
    Route::resource('property','PropertyCtrl');
    Route::resource('contact','ContactCtrl');
    Route::resource('region','RegionCtrl');
    Route::resource('blog','BlogCtrl');
    Route::resource('unitTypes','UnitTypesCtrl');
    Route::resource('slider','SliderController');

});

Route::get('{type}/{region}/{city}/{property:slug}/{name}','\App\Http\Controllers\FrontController@SingleProperty')->name('single.property')->where('type','resale|rent');

Route::get('rent/{region?}/{city?}/{street?}/{type_for?}','\App\Http\Controllers\FrontController@rant')->name('rent');
Route::get('resale/{region?}/{city?}/{street?}/{type_for?}','\App\Http\Controllers\FrontController@resale')->name('resale');

Route::get('/{location}/{developer:slug}/{project:slug?}','\App\Http\Controllers\FrontController@SingleProject')->name('developer_project.show');


Route::get('/{developer:slug}','\App\Http\Controllers\FrontController@show')->name('developer.show');

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register'=>false]);

Route::redirect('/home', '/dashboard')->name('home');

Route::get('setLocale/{locale?}', 'FrontController@setLocale')->where('locale','en|ar')->name('locale');

Route::get('/','FrontController@main')->name('main');

Route::get('dashboard','FrontController@dashboard')->name('dashboard');
Route::get('pricing','FrontController@pricing')->name('pricing');
Route::get('location/{location:slug}','FrontController@location')->name('location');
Route::get('about','FrontController@about')->name('about_us');
Route::get('developer','FrontController@developers_page')->name('developer.index');
//Route::get('developer/{developer:slug}/projects/{project}','FrontController@SingleProject')->name('developer_project.show');
//Route::get('developer/{developer:slug}','FrontController@show')->name('developer.show');


Route::get('contact','FrontController@contact_create')->name('contact_us');

Route::post('contact_project_post/{project}','FrontController@contact_project_post')->name('contact_project_post');

Route::post('contact_property_post/{property}','FrontController@contact_property_post')->name('contact_property_post');

Route::get('project','FrontController@project')->name('project');
Route::get('property','FrontController@SubmitProperty')->name('SubmitProperty');
//Route::get('property/{property:slug}','FrontController@SingleProperty')->name('single.property');
//Route::get('project/{project:slug}','FrontController@SingleProject')->name('single.project');
Route::get('blog/{blog:slug}','FrontController@SingleBlog')->name('single.blog');
Route::get('blogs/','FrontController@blogs')->name('blogs');
//Route::get('rent','FrontController@rant')->name('rent');
//Route::get('resale','FrontController@resale')->name('resale');

Route::get('autocomplete','FrontController@autocomplete')->name('autocomplete');

Route::get('/home', 'HomeController@index')->name('change_locale');

app/Http/Controllers/Dashboard/BlogCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Blog\BlogCreateRequest;
use App\Http\Requests\Blog\BlogUpdateRequest;
use App\Models\Blog;
use Illuminate\Http\Request;

class BlogCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() {
        return view('dashboard.blog.index',['blogs'=>Blog::latest()->get()]);
    }

    public function create(){ return view('dashboard.blog.create'); }


    public function store(BlogCreateRequest $request){
        $validated=$request->validated();
        if ($request->hasFile(Blog::avatarFiled()??'image')) $validated[Blog::avatarFiled()??'image']=uploader($request->file(Blog::avatarFiled()??'image'));
        Blog::create($validated);
        alert()->success(__('main.blog'),__('main.created'));
        return  back();
    }

    public function show(Blog $blog){ return view('dashboard.blog.show',compact('blog')); }

    public function edit(Blog $blog){ return view('dashboard.blog.edit',compact('blog')); }

    public function update(BlogUpdateRequest $request, Blog $blog){
        $validated=$request->validated();
        if ($request->hasFile(Blog::avatarFiled()??'image')) $validated[Blog::avatarFiled()??'image']=uploader($request->file(Blog::avatarFiled()??'image'));
        $blog->update($validated);
        alert()->success(__('main.blog'),__('main.updated'));
        return  back();

    }

    public function destroy(Blog $blog){
        $blog->delete();
        alert()->success(__('main.blog'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/ContactCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContactCreateRequest;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }

    public function toggleStatus(Contact $contact){
        $contact->update(['read_at' => now()]);
        return back()->withSuccess(__('main.mark_as_read'));
    }
    public function index() { return view('dashboard.contact.index'); }

//    public function create(){ return view('dashboard.contact.create'); }


    public function store(ContactCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Contact::avatarSelectedFiled()??'image')) $validated[Contact::avatarSelectedFiled()??'image'];
        Contact::create($validated);
        alert()->success(__('main.contact'),__('main.created'));
        return  back();
    }

//    public function show(Contact $contact){ return view('dashboard.contact.show',compact('contact')); }

//    public function edit(Contact $contact){ return view('dashboard.contact.edit',compact('contact')); }
//
//    public function update(ContactUpdateRequest $request, Contact $contact){
//        $validated=$request->validated();
//        //if ($request->hasFile(Contact::avatarSelectedFiled()??'image')) $validated[Contact::avatarSelectedFiled()??'image'];
//        $contact->update($validated);
//        alert()->success(__('main.contact'),__('main.updated'));
//        return  back();
//
//    }

    public function destroy(Contact $contact){
        $contact->delete();
        alert()->success(__('main.contact'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use App\Models\User;
use foo\bar;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

class DashboardController extends Controller{

    public function index() { return view('dashboard.blank'); }

    public function contactUs(){ return view('dashboard.contact'); }
    //
    public function change_password(){ return view('dashboard.profile.change_password'); }
    public function change_password_user(Request $request){
        $request->validate([
            'current_password' => ['required', 'string', 'min:8'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        $user=auth()->user();
        /**
         * @var $user User
         */
        if (!$user->comparePassword($request->get('current_password'))){
            return back()->withErrors([ "current_password"=>__('main.current_password_not_match')]);
        }



        if ($user->comparePassword($request->get('password'))){
            alert()->info(__('main.profile'),__('main.password_old_and_new_same'));
        }else{
            $user->update([
                'password' => $request->get('password')
            ]);
            alert()->success(__('main.profile'),__('main.password_changed_success'));
        }
        return back();
    }

}

app/Http/Controllers/Dashboard/DevCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Developer;
use Exception;

class DevCtrl extends Controller{

    public function index(){ return view('dashboard.developer.index'); }
    public function create(){ return view('dashboard.developer.create'); }
    public function show(Developer $developer){ return view('dashboard.developer.show',compact('developer')); }

    public function delete(Developer $developer){
        try {
            $developer->delete();
            alert()->success(__('main.developer'),__('main.developer_deleted'));
        } catch (Exception $e) {
        alert()->error(__('main.error_title_ERORR',$e->getMessage()));
        }
        return back();
    }

    public function edit(Developer $developer){ return view('dashboard.developer.edit',compact('developer')); }

}

app/Http/Controllers/Dashboard/OwnerCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Owner\OwnerCreateRequest;
use App\Http\Requests\Owner\OwnerUpdateRequest;
use App\Models\Owner;
use Illuminate\Http\Request;

class OwnerCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.owner.index'); }

    public function create(){ return view('dashboard.owner.create'); }


    public function store(OwnerCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Owner::avatarSelectedFiled()??'image')) $validated[Owner::avatarSelectedFiled()??'image'];
        Owner::create($validated);
        alert()->success(__('main.owner'),__('main.created'));
        return  back();
    }

    public function show(Owner $owner){ return view('dashboard.owner.show',compact('owner')); }

    public function edit(Owner $owner){ return view('dashboard.owner.edit',compact('owner')); }

    public function update(OwnerUpdateRequest $request, Owner $owner){
        $validated=$request->validated();
        //if ($request->hasFile(Owner::avatarSelectedFiled()??'image')) $validated[Owner::avatarSelectedFiled()??'image'];
        $owner->update($validated);
        alert()->success(__('main.owner'),__('main.updated'));
        return  back();

    }

    public function destroy(Owner $owner){
        $owner->delete();
        alert()->success(__('main.owner'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/ProjectCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Project\ProjectCreateRequest;
use App\Http\Requests\Project\ProjectUpdateRequest;
use App\Models\Project;
use Illuminate\Http\Request;

class ProjectCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.project.index'); }

    public function create(){ return view('dashboard.project.create'); }


    public function store(ProjectCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Project::avatarSelectedFiled()??'image')) $validated[Project::avatarSelectedFiled()??'image'];
        Project::create($validated);
        alert()->success(__('main.project'),__('main.created'));
        return  back();
    }

    public function show(Project $project){ return view('dashboard.project.show',compact('project')); }

    public function edit(Project $project){ return view('dashboard.project.edit',compact('project')); }

    public function update(ProjectUpdateRequest $request, Project $project){
        $validated=$request->validated();
        //if ($request->hasFile(Project::avatarSelectedFiled()??'image')) $validated[Project::avatarSelectedFiled()??'image'];
        $project->update($validated);
        alert()->success(__('main.project'),__('main.updated'));
        return  back();

    }

    public function destroy(Project $project){
        $project->delete();
        alert()->success(__('main.project'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/PropertyCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Property\PropertyCreateRequest;
use App\Http\Requests\Property\PropertyUpdateRequest;
use App\Models\Property;
use Illuminate\Http\Request;

class PropertyCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.property.index'); }

    public function create(){ return view('dashboard.property.create'); }

    public function toggleActive(Property $property){
        $property->update(['active' => !$property->active]);
        return back()->withSuccess($property->active?__('main.active'):__('main.not_active'));
    }

    public function store(PropertyCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Property::avatarSelectedFiled()??'image')) $validated[Property::avatarSelectedFiled()??'image'];
        Property::create($validated);
        alert()->success(__('main.property'),__('main.created'));
        return  back();
    }

    public function show(Property $property){ return view('dashboard.property.show',compact('property')); }

    public function edit(Property $property){ return view('dashboard.property.edit',compact('property')); }

    public function update(PropertyUpdateRequest $request, Property $property){
        $validated=$request->validated();
        //if ($request->hasFile(Property::avatarSelectedFiled()??'image')) $validated[Property::avatarSelectedFiled()??'image'];
        $property->update($validated);
        alert()->success(__('main.property'),__('main.updated'));
        return  back();

    }

    public function destroy(Property $property){
        $property->delete();
        alert()->success(__('main.property'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/RegionCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Region\RegionCreateRequest;
use App\Http\Requests\Region\RegionUpdateRequest;
use App\Models\Region;
use Illuminate\Http\Request;

class RegionCtrl extends Controller{
    public function __construct(){
        //$this->middleware(['']);
    }
    public function index() { return view('dashboard.region.index'); }

    public function create(){ return view('dashboard.region.create'); }


    public function store(RegionCreateRequest $request){
        $validated=$request->validated();
        //if ($request->hasFile(Region::avatarSelectedFiled()??'image')) $validated[Region::avatarSelectedFiled()??'image'];
        Region::create($validated);
        alert()->success(__('main.region'),__('main.created'));
        return  back();
    }

    public function show(Region $region){ return view('dashboard.region.show',compact('region')); }

    public function edit(Region $region){ return view('dashboard.region.edit',compact('region')); }

    public function update(RegionUpdateRequest $request, Region $region){
        $validated=$request->validated();
        //if ($request->hasFile(Region::avatarSelectedFiled()??'image')) $validated[Region::avatarSelectedFiled()??'image'];
        $region->update($validated);
        alert()->success(__('main.region'),__('main.updated'));
        return  back();

    }

    public function destroy(Region $region){
        $region->delete();
        alert()->success(__('main.region'),__('main.deleted'));
        return  back();
    }

}

app/Http/Controllers/Dashboard/SettingCtrl.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Setting\SettingCreateRequest;
use App\Http\Requests\Setting\SettingUpdateRequest;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingCtrl extends Controller{
    public function __construct(){ $this->middleware(['auth']); }

    public function index() { return view('dashboard.setting.index'); }

    public function update(SettingUpdateRequest $request, Setting $setting){
        $validated=$request->validated();
        //if ($request->hasFile(Setting::avatarSelectedFiled()??'image')) $validated[Setting::avatarSelectedFiled()??'image'];
        $setting->update($validated);
        alert()->success(__('main.setting'),__('main.updated'));
        return  back();

    }

    public function destroy(Setting $setting){
        $setting->delete();
        alert()->success(__('main.setting'),__('main.deleted'));
        return  back();
    }

}

resources/views/dashboard/slider/create.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>trans('main.owner_create')])
        <form action="{{route('dashboard.slider.store')}}" method="post" enctype="multipart/form-data">@csrf
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="image">@lang('main.image')</label>
                        <input type="file" onchange="readURL(this,'imgPre')" class="form-control" name="image" id="image" aria-describedby="helpId" placeholder="@lang('main.image')">
                        <x-errors.validation-error name="image"/>
                    </div>
                    <div class="form-group">
                        <label for="order_by">@lang('main.order_by')</label>
                        <input type="number" class="form-control" name="order_by" value="{{old('order_by',($order_by=\App\Models\Slider::latest('order_by')->first())?$order_by->order_by+1:1)}}" id="order_by" aria-describedby="helpId" placeholder="@lang('main.order_by')">
                        <x-errors.validation-error name="order_by"/>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="img-thumbnail">
                        <img src="" id="imgPre" class="w-100" alt="">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">@lang('main.save')</button>
        </form>
    @endcomponent


@stop

resources/views/dashboard/slider/edit.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>trans('main.slider_edit')])
        <form action="{{route('dashboard.slider.update',$slider)}}" method="post" enctype="multipart/form-data">@csrf @method('PUT')
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="image">@lang('main.image')</label>
                        <input type="file" onchange="readURL(this,'imgPre')" class="form-control" name="image" id="image" aria-describedby="helpId" placeholder="@lang('main.image')">
                        <x-errors.validation-error name="image"/>
                    </div>
                    <div class="form-group">
                        <label for="order_by">@lang('main.order_by')</label>
                        <input type="number" class="form-control" name="order_by" value="{{old('order_by',$slider->order_by)}}" id="order_by" aria-describedby="helpId" placeholder="@lang('main.order_by')">
                        <x-errors.validation-error name="order_by"/>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="img-thumbnail">
                        <img src="{{$slider->imagePath}}" id="imgPre" class="w-100" alt="">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">@lang('main.save')</button>
        </form>


    @endcomponent


@stop

resources/views/dashboard/slider/index.blade.php
@extends('layouts.dashboard.dashboard')
@push('css')
    <link href="{{asset('vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endpush
@push('js')
    <script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
@endpush
@section('content')
    @component('card-component',['title'=>ucfirst(trans('main.sliders'))])

        @component('components.data-table',['tableID'=>"tableslider"])
            @slot('thead')
                <tr>
                    <th> @lang('main.id') </th>
                    <th>@lang('main.order_by')</th>
                    <th>@lang('main.image')</th>
                    <th> @lang('main.edit') </th>
                    <th> @lang('main.delete') </th>
                </tr>
            @endslot
            @slot('tbody')
                @foreach ($sliders as $slider)
                    <tr>
                        <td>{{$slider->id}}</td>
                        <td>{{$slider->order_by}}</td>
                        <td><img height="100" src="{{$slider->imagePath}}" alt=""></td>
                        <td>
                            <a href="{{route('dashboard.slider.edit',$slider)}}" class="btn btn-sm btn-warning">@lang('main.edit')</a>
                        </td>
                        <td>
                            <form name="sliderDelete{{$slider->id}}" action="{{route('dashboard.slider.destroy',$slider)}}" method="post">@csrf @method('DELETE')</form>
                            <button type="button" onclick="confirm(' @lang('main.slider_delete') ')?sliderDelete{{$slider->id}}.submit():''" class="btn btn-sm btn-danger">@lang('main.delete')</button>
                        </td>
                    </tr>
                @endforeach
            @endslot

        @endcomponent

        <div class="text-right"> <div class="d-inline-block"></div> </div>

        @push('js')
            <script>
                $(document).ready(function() {
                    $('#tableslider').DataTable({
                        // paginate:false
                    });
                });
            </script>
        @endpush


    @endcomponent


@stop

resources/views/dashboard/slider/show.blade.php
@extends('layouts.dashboard.dashboard')

@section('content')
    @component('card-component',['title'=>trans('main.developer')])


    @endcomponent


@stop